# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Product Designer & Front-End Developer
email: aalarner#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! My name is Abby, and I have spent
  the past five years honing my skills by working
  on a variety of mobile and web applications
  with companies both large and small.
  I strive to design experiences that combine
  simplicity, functionality, and fun.
  I’m excited about building strong
  communities that emphasizes collaboration,
  learning, and personal growth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abbylarner.com" # the base hostname & protocol for your site
twitter_username: '@abbylarner'
github_username:  '@abbylarner'

# Build settings
markdown: kramdown
